# Generated by Django 4.1.2 on 2023-04-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default='kFV81M6hlN', max_length=10, unique=True),
        ),
    ]
