# Generated by Django 4.1.2 on 2023-04-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_payment_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default='Lrn4k7SLE6', max_length=10, unique=True),
        ),
    ]
