# Generated by Django 4.1.2 on 2023-08-13 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('last_updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pharmacy.basemodel')),
                ('pharmacy_profile_pic', models.ImageField(default='default/pharmacy-d.jpg', upload_to='pharmacy/profile/')),
                ('pharmacy_pincode', models.IntegerField()),
                ('pharmacy_city', models.CharField(max_length=60)),
                ('pharmacy_address', models.CharField(max_length=200)),
                ('pharmacy_description', models.TextField()),
                ('pharmacy_phone', models.CharField(max_length=60)),
                ('pharmacy_rating', models.FloatField(default=0)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_profile', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('pharmacy.basemodel',),
        ),
        migrations.CreateModel(
            name='PharmacyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('pharmacy_reg_no', models.CharField(max_length=32)),
                ('phone_number', models.CharField(max_length=20)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('is_phone_verified', models.BooleanField(default=False)),
                ('phone_otp', models.CharField(blank=True, max_length=200, null=True)),
                ('email_otp', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_otp_creation', models.DateTimeField(blank=True, null=True)),
                ('email_otp_creation', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_extd', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PharmaReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('review', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('created_at', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_reviewed_by', to='app.userprofile')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_review', to='pharmacy.pharmacy')),
            ],
        ),
    ]
