# Generated by Django 4.1.2 on 2023-04-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='pharmacy_profile_pic',
            field=models.ImageField(default='default/pharmacy-d.jpg', upload_to='pharmacy/profile/'),
        ),
    ]
