# Generated by Django 4.1.2 on 2023-08-13 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('last_updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.basemodel')),
                ('full_name', models.CharField(max_length=60)),
                ('profile_pic', models.ImageField(blank=True, default='default/d-user.jpg', null=True, upload_to='user/profile/')),
                ('age', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(blank=True, default='Male', max_length=8, null=True)),
                ('phone', models.IntegerField()),
                ('city', models.CharField(max_length=16)),
                ('pincode', models.IntegerField()),
                ('address', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('app.basemodel',),
        ),
    ]
