# Generated by Django 4.1.2 on 2023-08-13 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pharmacy', '0001_initial'),
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('last_updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='doctor.basemodel')),
                ('doctor_name', models.CharField(max_length=60)),
                ('doctor_degree', models.CharField(max_length=100)),
                ('doctor_reg_no', models.CharField(max_length=20)),
                ('doctor_gender', models.CharField(max_length=8)),
                ('doctor_speciality', models.TextField()),
                ('doctor_phone', models.CharField(max_length=60)),
                ('doctor_description', models.TextField()),
                ('doctor_profile_pic', models.ImageField(default='default/doctor-d.jpg', upload_to='doctors/profile/')),
                ('doctor_services', models.TextField(blank=True, null=True)),
                ('doctor_work_experience', models.TextField(blank=True, null=True)),
                ('doctor_fees', models.FloatField()),
                ('doctor_rating', models.FloatField(default=0)),
                ('doctor_address', models.CharField(blank=True, max_length=256, null=True)),
                ('pharmacies', models.ManyToManyField(to='pharmacy.pharmacy')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('doctor.basemodel',),
        ),
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField(default=15)),
                ('total_booked', models.PositiveIntegerField(default=0)),
                ('fees', models.FloatField()),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_schedule', to='pharmacy.pharmacy')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_schedule', to='doctor.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('review', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('created_at', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_reviewed_by', to='app.userprofile')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_review', to='doctor.doctor')),
            ],
        ),
    ]
